data:
    batch_size: 32
    num_workers: 4
    image_size: 224
    image_path: "../../dataset/flickr/flickr30k_images"
    captions_path: "../../dataset/flickr"
    max_length: 200
    debug: False
model:
    image_encoder:
        model_name: "resnet50"
        pretrained: True
        trainable: True
    text_encoder:
        model_name: "distilbert-base-uncased"
        pretrained: True
        trainable: True
    projection_head:
        projection_dim: 256
        dropout: 0.1
    clip:
        temperature: 1.0
        image_embedding: 2048
        text_embedding: 768
train:
    epoch: 10
    text_tokenizer: "distilbert-base-uncased"
    image_encoder_lr: 0.0001
    text_encoder_lr: 0.00001
    head_lr: 0.001
    weight_decay: 0.001
    patience: 1
    factor: 0.8

